import type { Employee, KeyRole, CrossProject, CorporateTask } from './types';

// ============================================================
//  Sample Talent Pool — Yum China style (KFC / Pizza Hut / etc.)
// ============================================================

export const EMPLOYEES: Employee[] = [
  {
    id: 'E001',
    name: '王晨',
    avatar: '👩‍💼',
    title: '华东区营运总监',
    band: 'M5',
    brand: '肯德基',
    department: '营运',
    location: '上海',
    tenureYears: 11,
    performance: 'A',
    potential: '高潜',
    readiness: 'Ready Now',
    successorOf: '肯德基营运副总裁',
    competencies: [
      { name: '战略思维', score: 88 },
      { name: '业务领导力', score: 92 },
      { name: '人才发展', score: 85 },
      { name: '数字化敏锐', score: 70 },
      { name: '跨界协作', score: 78 },
      { name: '客户洞察', score: 90 },
    ],
    skills: ['门店营运', 'P&L 管理', '区域扩张', '数字化点餐', 'OKR'],
    experiences: ['华东 1200 家门店营运', '主导 KFC 早餐场景升级', '跨品牌轮岗（必胜客 1 年）'],
    certifications: ['Capgemini Leadership Sprint'],
    bio: '11 年深耕营运，曾带领华东大区在疫情周期内实现同店增长 8%，具备跨品牌经验，是营运 VP 的核心后备人选。',
    riskFlags: [],
  },
  {
    id: 'E002',
    name: '李哲',
    avatar: '🧑‍💻',
    title: '数字化产品高级经理',
    band: 'M3',
    brand: '集团总部',
    department: '数字化与技术',
    location: '上海',
    tenureYears: 6,
    performance: 'A',
    potential: '高潜',
    readiness: '1-2年',
    successorOf: '数字化产品总监',
    competencies: [
      { name: '战略思维', score: 78 },
      { name: '业务领导力', score: 72 },
      { name: '人才发展', score: 65 },
      { name: '数字化敏锐', score: 95 },
      { name: '跨界协作', score: 88 },
      { name: '客户洞察', score: 82 },
    ],
    skills: ['会员体系', '小程序', 'A/B 实验', 'GenAI', '数据分析'],
    experiences: ['超级 App 会员重构', '小程序点餐 GMV +35%', '与营运 BU 联合发布会员等级'],
    certifications: ['Google Cloud PM'],
    bio: '会员与小程序方向负责人，强数据驱动，缺乏大团队管理与跨品牌历练。',
  },
  {
    id: 'E003',
    name: '陈宇',
    avatar: '👨‍🍳',
    title: '必胜客产品创新经理',
    band: 'M3',
    brand: '必胜客',
    department: '产品与菜单',
    location: '上海',
    tenureYears: 8,
    performance: 'B+',
    potential: '高潜',
    readiness: '1-2年',
    competencies: [
      { name: '战略思维', score: 70 },
      { name: '业务领导力', score: 75 },
      { name: '人才发展', score: 60 },
      { name: '数字化敏锐', score: 65 },
      { name: '跨界协作', score: 80 },
      { name: '客户洞察', score: 93 },
    ],
    skills: ['新品研发', '消费者洞察', '供应链协同', '门店落地', '本地化创新'],
    experiences: ['主导榴莲披萨系列', '推动必胜客早午餐场景', '与黄记煌联合中餐研发'],
    bio: '产品创新主力，对中式餐饮场景敏感，曾跨品牌支持过黄记煌中餐 SKU 重构。',
  },
  {
    id: 'E004',
    name: '赵敏',
    avatar: '👩‍🔬',
    title: '供应链高级分析师',
    band: 'P4',
    brand: '集团总部',
    department: '供应链',
    location: '上海',
    tenureYears: 5,
    performance: 'A',
    potential: '高潜',
    readiness: '1-2年',
    competencies: [
      { name: '战略思维', score: 75 },
      { name: '业务领导力', score: 60 },
      { name: '人才发展', score: 55 },
      { name: '数字化敏锐', score: 92 },
      { name: '跨界协作', score: 82 },
      { name: '客户洞察', score: 65 },
    ],
    skills: ['需求预测', '运筹优化', 'Python', '冷链', 'SAP'],
    experiences: ['门店需求预测模型', '冷链网络重构 PMO', '与必胜客协同库存项目'],
    certifications: ['CPIM'],
    bio: '供应链分析骨干，主导过门店需求预测模型重构，跨品牌经验需补强。',
  },
  {
    id: 'E005',
    name: '孙雷',
    avatar: '👨‍💼',
    title: '区域营运经理',
    band: 'M4',
    brand: '肯德基',
    department: '营运',
    location: '北京',
    tenureYears: 14,
    performance: 'B+',
    potential: '稳定',
    readiness: '3-5年',
    competencies: [
      { name: '战略思维', score: 65 },
      { name: '业务领导力', score: 82 },
      { name: '人才发展', score: 78 },
      { name: '数字化敏锐', score: 55 },
      { name: '跨界协作', score: 65 },
      { name: '客户洞察', score: 80 },
    ],
    skills: ['门店运营', '人才梯队', '区域拓展'],
    experiences: ['北京区域门店扩张 +120 家', '门店店长培养 50+'],
    bio: '资深营运，门店一线经验丰富，数字化敏锐度需要提升。',
  },
  {
    id: 'E006',
    name: '周悦',
    avatar: '👩‍🎓',
    title: '人才发展高级经理',
    band: 'M3',
    brand: '集团总部',
    department: '人力资源',
    location: '上海',
    tenureYears: 7,
    performance: 'A',
    potential: '高潜',
    readiness: '1-2年',
    competencies: [
      { name: '战略思维', score: 78 },
      { name: '业务领导力', score: 72 },
      { name: '人才发展', score: 95 },
      { name: '数字化敏锐', score: 75 },
      { name: '跨界协作', score: 85 },
      { name: '客户洞察', score: 70 },
    ],
    skills: ['继任规划', '九宫格盘点', '领导力发展', 'OD 设计', '教练'],
    experiences: ['集团人才盘点项目负责人', '餐厅大学课程设计', '跨品牌轮岗机制设计'],
    bio: '人才发展专家，主导集团高潜池盘点和"餐厅大学"课程升级。',
  },
  {
    id: 'E007',
    name: '吴磊',
    avatar: '🧑‍🏫',
    title: '餐厅大学讲师 / OD',
    band: 'P4',
    brand: '集团总部',
    department: '人力资源',
    location: '上海',
    tenureYears: 9,
    performance: 'B+',
    potential: '稳定',
    readiness: '3-5年',
    competencies: [
      { name: '战略思维', score: 60 },
      { name: '业务领导力', score: 65 },
      { name: '人才发展', score: 88 },
      { name: '数字化敏锐', score: 60 },
      { name: '跨界协作', score: 78 },
      { name: '客户洞察', score: 68 },
    ],
    skills: ['课程设计', '培训交付', '导师机制', '行动学习'],
    experiences: ['店长养成项目主讲', '区域经理领导力课程'],
    bio: '资深讲师，营运体系内部影响力高。',
  },
  {
    id: 'E008',
    name: '黄薇',
    avatar: '👩‍🚀',
    title: '塔可贝尔品牌市场副总监',
    band: 'M4',
    brand: '塔可贝尔',
    department: '市场',
    location: '上海',
    tenureYears: 4,
    performance: 'A',
    potential: '高潜',
    readiness: 'Ready Now',
    successorOf: '塔可贝尔品牌市场总监',
    competencies: [
      { name: '战略思维', score: 85 },
      { name: '业务领导力', score: 80 },
      { name: '人才发展', score: 72 },
      { name: '数字化敏锐', score: 88 },
      { name: '跨界协作', score: 90 },
      { name: '客户洞察', score: 92 },
    ],
    skills: ['品牌定位', '新品上市', '社交媒体', '本地化营销', 'GenAI 内容生产'],
    experiences: ['塔可贝尔上海首店开业战役', '小红书种草矩阵搭建'],
    bio: '新兴品牌孵化经验，对 Z 世代消费洞察突出，跨品牌可复用性强。',
    riskFlags: ['市场对标 offer 风险'],
  },
  {
    id: 'E009',
    name: '林涛',
    avatar: '👨‍🔧',
    title: '门店技术运维经理',
    band: 'M3',
    brand: '集团总部',
    department: '数字化与技术',
    location: '深圳',
    tenureYears: 6,
    performance: 'B+',
    potential: '稳定',
    readiness: '3-5年',
    competencies: [
      { name: '战略思维', score: 55 },
      { name: '业务领导力', score: 65 },
      { name: '人才发展', score: 60 },
      { name: '数字化敏锐', score: 88 },
      { name: '跨界协作', score: 70 },
      { name: '客户洞察', score: 60 },
    ],
    skills: ['POS', '门店设备', '云架构', 'SRE'],
    experiences: ['华南 800 家门店 POS 升级', '门店智能设备试点'],
    bio: '技术骨干，门店侧 IT 落地经验扎实。',
  },
  {
    id: 'E010',
    name: '何静',
    avatar: '👩‍⚖️',
    title: '法务与合规经理',
    band: 'M3',
    brand: '集团总部',
    department: '法务',
    location: '上海',
    tenureYears: 8,
    performance: 'B+',
    potential: '稳定',
    readiness: '3-5年',
    competencies: [
      { name: '战略思维', score: 72 },
      { name: '业务领导力', score: 65 },
      { name: '人才发展', score: 60 },
      { name: '数字化敏锐', score: 70 },
      { name: '跨界协作', score: 75 },
      { name: '客户洞察', score: 70 },
    ],
    skills: ['数据合规', '个人信息保护法', '商务合同', '反垄断'],
    experiences: ['会员数据合规重构', '与数字化团队合规联合工作组'],
    bio: '熟悉数据合规与个保法，是数字化项目重要合规伙伴。',
  },
  {
    id: 'E011',
    name: '张涵',
    avatar: '🧑‍🎨',
    title: '用户体验设计师',
    band: 'P3',
    brand: '集团总部',
    department: '数字化与技术',
    location: '上海',
    tenureYears: 3,
    performance: 'A',
    potential: '高潜',
    readiness: '1-2年',
    competencies: [
      { name: '战略思维', score: 60 },
      { name: '业务领导力', score: 55 },
      { name: '人才发展', score: 50 },
      { name: '数字化敏锐', score: 85 },
      { name: '跨界协作', score: 82 },
      { name: '客户洞察', score: 90 },
    ],
    skills: ['UX 研究', 'Figma', '服务设计', '会员旅程'],
    experiences: ['小程序点餐重构主设计', '会员旅程地图'],
    bio: '年轻设计骨干，跨业务 UX 思维出色。',
  },
  {
    id: 'E012',
    name: '徐凯',
    avatar: '👨‍🏫',
    title: '黄记煌营运总监',
    band: 'M4',
    brand: '黄记煌',
    department: '营运',
    location: '北京',
    tenureYears: 12,
    performance: 'B+',
    potential: '高潜',
    readiness: '1-2年',
    successorOf: '黄记煌品牌总经理',
    competencies: [
      { name: '战略思维', score: 78 },
      { name: '业务领导力', score: 82 },
      { name: '人才发展', score: 72 },
      { name: '数字化敏锐', score: 60 },
      { name: '跨界协作', score: 70 },
      { name: '客户洞察', score: 85 },
    ],
    skills: ['中式餐饮营运', '加盟体系', '门店扩张'],
    experiences: ['黄记煌品牌升级项目', '北方区开店翻番'],
    bio: '中式餐饮营运背景，理解新兴品牌孵化。',
  },
];

// ============================================================
//  Key Roles (关键岗位)
// ============================================================
export const KEY_ROLES: KeyRole[] = [
  {
    id: 'R-KFC-OPS',
    title: '肯德基营运副总裁 (VP, Operations)',
    brand: '肯德基',
    incumbent: '现任 VP（计划 18 个月内轮岗）',
    vacancyRisk: 'High',
    successorCount: 2,
    requiredSkills: ['大区营运', '战略执行', '人才发展', 'P&L', '数字化敏锐'],
    strategicWeight: 95,
    scarcity: 85,
    replaceDifficulty: 88,
  },
  {
    id: 'R-DIG-DIR',
    title: '数字化产品总监 (Digital Product Director)',
    brand: '集团总部',
    incumbent: '空缺，6 个月内须填补',
    vacancyRisk: 'High',
    successorCount: 1,
    requiredSkills: ['会员产品', '组织管理', 'GenAI 落地', '跨 BU 沟通'],
    strategicWeight: 88,
    scarcity: 90,
    replaceDifficulty: 80,
  },
  {
    id: 'R-PH-INNO',
    title: '必胜客创新总监 (Pizza Hut Innovation Director)',
    brand: '必胜客',
    incumbent: '现任在岗',
    vacancyRisk: 'Medium',
    successorCount: 2,
    requiredSkills: ['品类创新', '消费者洞察', '供应链协同', '门店运营'],
    strategicWeight: 80,
    scarcity: 70,
    replaceDifficulty: 72,
  },
  {
    id: 'R-TAC-MKT',
    title: '塔可贝尔品牌市场总监',
    brand: '塔可贝尔',
    incumbent: '空缺',
    vacancyRisk: 'High',
    successorCount: 1,
    requiredSkills: ['新兴品牌孵化', '社媒营销', 'Z 世代洞察', '本地化'],
    strategicWeight: 78,
    scarcity: 88,
    replaceDifficulty: 75,
  },
];

// ============================================================
//  Cross-functional Projects (跨部门项目)
// ============================================================
export const CROSS_PROJECTS: CrossProject[] = [
  {
    id: 'P-MEM-2026',
    name: '集团超级会员体系 2.0',
    brand: '集团总部',
    duration: '6 个月',
    description: '统一肯德基/必胜客/塔可贝尔会员资产，打通积分与权益，引入 AI 个性化推荐。',
    roles: [
      { role: '产品负责人', skills: ['会员体系', 'A/B 实验', '跨 BU 沟通'] },
      { role: '数据科学家', skills: ['推荐算法', '需求预测', 'Python'] },
      { role: '体验设计师', skills: ['服务设计', '会员旅程', 'Figma'] },
      { role: '合规顾问', skills: ['个保法', '数据合规'] },
    ],
  },
  {
    id: 'P-DIG-STORE',
    name: '智慧门店运营试点',
    brand: '肯德基',
    duration: '4 个月',
    description: '面向 200 家试点门店落地 AI 排班、动态备餐与客流洞察，目标人效 +6%。',
    roles: [
      { role: '项目经理', skills: ['门店运营', '项目管理', 'PMO'] },
      { role: '数据分析师', skills: ['需求预测', 'SAP', 'Python'] },
      { role: 'IT 落地', skills: ['POS', '门店设备', '云架构'] },
    ],
  },
  {
    id: 'P-CN-NEW',
    name: '中餐品牌组合协同孵化',
    brand: '黄记煌',
    duration: '5 个月',
    description: '黄记煌 / 小肥羊 / 必胜客中餐场景的菜单协同、供应链协同与人才共享。',
    roles: [
      { role: '产品创新', skills: ['新品研发', '消费者洞察', '本地化创新'] },
      { role: '营运代表', skills: ['中式餐饮营运', '加盟体系'] },
      { role: '供应链', skills: ['冷链', '需求预测'] },
    ],
  },
];

// ============================================================
//  Corporate Tasks (集团级测试任务)
// ============================================================
export const CORPORATE_TASKS: CorporateTask[] = [
  {
    id: 'T-AI-COE',
    title: 'GenAI 卓越中心 (CoE) 筹建',
    sponsor: 'CIO Office',
    description: '搭建集团级 GenAI CoE，覆盖治理、用例孵化与人才认证。',
    requiredSkills: ['GenAI', '组织设计', '跨 BU 沟通', '战略思维'],
    durationWeeks: 16,
  },
  {
    id: 'T-LEADER',
    title: '高潜领导力沙盘 2026',
    sponsor: 'CHRO',
    description: '面向 Top 80 高潜的为期 8 周战略沙盘项目。',
    requiredSkills: ['战略思维', '业务领导力', '人才发展'],
    durationWeeks: 8,
  },
  {
    id: 'T-ESG',
    title: 'ESG 数据透明化攻坚',
    sponsor: 'CFO',
    description: '完成集团 ESG 报告所需的数据治理与流程标准化。',
    requiredSkills: ['数据合规', '数据治理', '跨 BU 沟通'],
    durationWeeks: 10,
  },
];

// ============================================================
//  Capgemini Assets & Cases (凯捷资产 / 案例)
// ============================================================
export const CAPGEMINI_ASSETS = [
  { name: 'SAP SF 人才画像组件', category: 'HCM 资产', desc: '基于 SuccessFactors 扩展的多维人才画像，能力 / 经历 / 潜力维度可配置。' },
  { name: 'AI 人岗匹配引擎', category: 'AI 资产', desc: '基于技能向量相似度的匹配模型，已沉淀 300+ 用例 gallery。' },
  { name: 'AI 简历分析', category: 'AI 资产', desc: 'OCR + LLM 简历结构化与能力反推。' },
  { name: 'SF 继任发展模块', category: 'HCM 资产', desc: '继任池构建、九宫格盘点与发展计划落地经验。' },
  { name: '黄金数据源原则', category: '数据治理', desc: '多源数据冲突解决与黄金源认定，已用于奇瑞、华润、招商局。' },
  { name: 'Gen AI for HR', category: 'GenAI 方案', desc: '主管发展建议书自动生成、员工教练机器人、面试题智能生成。' },
];

export const CAPGEMINI_CASES = [
  { client: '奇瑞汽车', highlight: 'HRSSC + SF 全模块；建立集团人才画像与继任池，对客户感受高度匹配本项目。' },
  { client: '麦当劳 (餐饮业)', highlight: '门店人才与营运赋能，餐饮行业 know-how 直接可复用。' },
  { client: '一汽大众', highlight: 'SF 继任发展 + 目标绩效，深度跨 BU 人才流动机制。' },
  { client: '安踏集团', highlight: '继任管理 + 员工发展计划 + 学习管理一体化。' },
  { client: '招商局', highlight: '集团化管控人才数字化转型，多源数据治理。' },
  { client: '立邦中国', highlight: '继任者管理 + 员工发展 + 360 度测评 + WFA。' },
];

export const NAV = [
  { key: 'overview', label: '项目理解', icon: 'home' },
  { key: 'dashboard', label: '组织驾驶舱', icon: 'gauge' },
  { key: 'employee', label: '员工自助', icon: 'user' },
  { key: 'manager', label: '主管视角', icon: 'briefcase' },
  { key: 'recommendation', label: '智能推荐引擎', icon: 'sparkles' },
  { key: 'methodology', label: '凯捷方案与方法论', icon: 'layers' },
] as const;
